server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/proyecto3
    username: postgres
    password: sasa
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: asdfafasfasdfasfasfdasdfasfasdffsdfasdfasdfasdfasdfasdfasdfasfdasdfasfdasdfasdfasfdasdfasdfasdfasdfasdfasdfasdfasdfasdfasasaasasaassaasasasasd